// transitions will be added later

export const TEXT_STYLE_PRESETS = [
  {
    id: 'mrbeast',
    name: 'MrBeast',
    category: 'viral',
    fontFamily: 'Impact, Anton, "Arial Black", sans-serif',
    fontSize: 86,
    color: '#FFE600',
    stroke: '#000000',
    textTransform: 'uppercase',
    letterSpacing: '1.6px',
    lineHeight: 1.05,
    background: null,
    shadow: '0 4px 8px rgba(0,0,0,0.55)',
    animation: 'none',
  },
  {
    id: 'tiktok-bold',
    name: 'TikTok Bold',
    category: 'viral',
    fontFamily: 'Inter, "SF Pro Display", sans-serif',
    fontSize: 74,
    color: '#FFFFFF',
    stroke: '#111827',
    textTransform: 'none',
    letterSpacing: '0.2px',
    lineHeight: 1.1,
    background: null,
    shadow: '0 6px 16px rgba(0,0,0,0.65)',
    animation: 'none',
  },
  {
    id: 'reel-pop',
    name: 'Reel Pop',
    category: 'viral',
    fontFamily: 'Montserrat, Poppins, sans-serif',
    fontSize: 78,
    color: '#FFFFFF',
    stroke: '#6B21A8',
    textTransform: 'uppercase',
    letterSpacing: '1px',
    lineHeight: 1.08,
    background: 'linear-gradient(90deg, #ec4899 0%, #f97316 100%)',
    shadow: '0 4px 14px rgba(236,72,153,0.45)',
    animation: 'none',
  },
  {
    id: 'podcast-subtitle',
    name: 'Podcast Subtitle',
    category: 'viral',
    fontFamily: 'Poppins, Inter, sans-serif',
    fontSize: 58,
    color: '#F8FAFC',
    stroke: '#0F172A',
    textTransform: 'none',
    letterSpacing: '0px',
    lineHeight: 1.18,
    background: 'rgba(2, 6, 23, 0.45)',
    shadow: '0 2px 10px rgba(0,0,0,0.35)',
    animation: 'none',
  },
  {
    id: 'gaming-highlight',
    name: 'Gaming Highlight',
    category: 'viral',
    fontFamily: 'Rajdhani, Orbitron, "Arial Black", sans-serif',
    fontSize: 82,
    color: '#7CFF6B',
    stroke: '#001A0E',
    textTransform: 'uppercase',
    letterSpacing: '1.4px',
    lineHeight: 1.04,
    background: null,
    shadow: '0 0 12px rgba(124,255,107,0.65)',
    animation: 'none',
  },
  {
    id: 'classic',
    name: 'Classic',
    category: 'basic',
    fontFamily: 'Poppins, sans-serif',
    fontSize: 48,
    color: '#FFFFFF',
    stroke: '#000000',
    textTransform: 'none',
    letterSpacing: '0px',
    lineHeight: 1.14,
    background: null,
    shadow: '0 2px 8px rgba(0,0,0,0.4)',
    animation: 'none',
  },
  {
    id: 'minimal',
    name: 'Minimal',
    category: 'basic',
    fontFamily: 'Inter, sans-serif',
    fontSize: 42,
    color: '#F8FAFC',
    stroke: '#111827',
    textTransform: 'none',
    letterSpacing: '0px',
    lineHeight: 1.2,
    background: null,
    shadow: '0 1px 4px rgba(0,0,0,0.3)',
    animation: 'none',
  },
  {
    id: 'youtube',
    name: 'YouTube',
    category: 'basic',
    fontFamily: 'Roboto, Arial, sans-serif',
    fontSize: 46,
    color: '#FFFFFF',
    stroke: '#000000',
    textTransform: 'none',
    letterSpacing: '0px',
    lineHeight: 1.15,
    background: 'rgba(0,0,0,0.35)',
    shadow: '0 1px 3px rgba(0,0,0,0.25)',
    animation: 'none',
  },
  {
    id: 'clean',
    name: 'Clean',
    category: 'basic',
    fontFamily: 'Nunito, Inter, sans-serif',
    fontSize: 44,
    color: '#F9FAFB',
    stroke: '#111827',
    textTransform: 'none',
    letterSpacing: '0.1px',
    lineHeight: 1.18,
    background: null,
    shadow: '0 1px 6px rgba(0,0,0,0.32)',
    animation: 'none',
  },
  {
    id: 'bold',
    name: 'Bold',
    category: 'basic',
    fontFamily: 'Montserrat, Poppins, sans-serif',
    fontSize: 52,
    color: '#FFFFFF',
    stroke: '#000000',
    textTransform: 'uppercase',
    letterSpacing: '0.8px',
    lineHeight: 1.1,
    background: null,
    shadow: '0 3px 10px rgba(0,0,0,0.45)',
    animation: 'none',
  },
];

export const VIRAL_TEXT_STYLES = TEXT_STYLE_PRESETS.filter((s) => s.category === 'viral');
export const BASIC_TEXT_STYLES = TEXT_STYLE_PRESETS.filter((s) => s.category === 'basic');

export const getTextStyleById = (id) =>
  TEXT_STYLE_PRESETS.find((style) => style.id === id) || TEXT_STYLE_PRESETS.find((s) => s.id === 'classic');
